name: ndpl
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_easyloading: ^3.0.5
  circular_bottom_navigation:
  flutter_widget_from_html_core: ^0.17.0
  package_info_plus:
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.2
  connectivity_plus: ^6.1.5
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    # - assets/fonts/SutonnyMJ_Regular.ttf


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_18pt-ExtraLightItalic.ttf
          weight: 700
    - family: Bangla
      fonts:
        - asset: assets/fonts/SutonnyMJ_Regular.ttf
